=== andigamesandmusic/belle/definitions/mica.dtd
<!--
  MICA (Music Information Concept Archive) DTD
  
  Version 1.0
  
  Copyright 2007-2013, 2017 Andi

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
-->

<!--
  The mica element may contain mappings and/or concept categories. A single
  mica XML file may thus describe a portion or all of the MICA dictionary.
  
	Suggested use:
	
	<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<!DOCTYPE mica PUBLIC
		"-//MICA//DTD Music Information Concept Archive//EN"
		"https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
-->

<!--
  The mica element may contain zero or more map and category elements. It has
  no attributes.
-->
<!ELEMENT mica (map | category)*>

<!--
  The map element contains a whitespace-separated list of language-localized
  identifiers. The mapping uses all but the last identifier as the input
  multiset and the last identifier as the output.
  
  Example:
  <map>en:A en:B en:C</map>           means {en:A en:B} -> en:C
  
  Note that the input is unordered. Therefore the following is equivalent:
  <map>en:B en:A en:C</map>      also means {en:A en:B} -> en:C
  
  The language-localized identifier must refer to an identifier element found
  elsewhere in the MICA dictionary (potentially in another XML file).
  
  For example, en:A refers to the concept containing the identifier tag:
  <identifier lang="en">A</identifier>
-->
<!ELEMENT map (#PCDATA)>

<!--
  The category element contains one or more definition and concept elements.
  
  A definition element is provided for each language-localization of the
  category name and definition. Categories are semantic groups used primarily
  for organization and documentation. They are not necessarily encoded in the
  programming language APIs.
  
  A concept element is provided to declare a concept that belongs to the given
  category.
  
  The contents of a category element may not be partially specified. All
  concepts and definitions relevant to the category must be contained in one
  tag (a single category may not spread across multiple files).
-->
<!ELEMENT category (definition | concept)+>

<!--
  The concept element contains an optional sequence element (if it represents a
  sequence) followed by one or more (programming language) identifier elements
  followed by zero or more (natural language) definition elements.
  
  The uuid attribute specifies either one of the language-localized identifiers
  specified within the concept (for example, en:QuarterNote) or a UUID in the
  canonical hex format:
  
  nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn
  
  Where n is a digit 0-9 or lowercase letter a-f. Uppercase letters must not
  be used (the UUID must be expressed in canonical lowercase form).
  
  Note that if a language-localized identifier is used, it is internally
  converted to a UUID via the MD5 namespace algorithm. The identifier thus
  uniquely maps to a UUID.
  
  ATTENTION:
  
  THE uuid ATTRIBUTE MUST NOT BE CHANGED TO ANOTHER IDENTIFIER AFTER IT IS SET.
  CHANGING THE uuid IDENTIFIER CHANGES THE UNDERLYING UUID ENCODING AND WILL
  REDEFINE THE CONCEPT TO A DIFFERENT NUMBER.
  
  In cases where the identifier must be changed, an error will be emitted during
  the parse if the identifier no longer exists and the uuid attribute must then
  be changed to use an explicit UUID representing the original UUID.
  Backwards-compatibility is a requirement of MICA. In these cases a comment
  should also be provided indicating the source of the original UUID.
-->

<!ELEMENT concept (sequence?, identifier+, definition*)>
<!ATTLIST concept
  uuid CDATA #REQUIRED>

<!--
  The identifier element provides the programming and natural language-localized
  identifier name of a concept to be used in the context of a programming
  language.
  
  The lang attribute specifies the language-localization using a two-letter
  lowercase ISO 639-1 language code optionally followed by a hyphen and a
  two-letter uppercase ISO 3166-2 country code optionally followed by a hyphen
  and the commonly accepted extension of a source code file in the target
  programming language.
  
  See the following examples.
  
  English identifier for generic programming language:  
  <identifier lang="en">QuarterNote</identifier>
  
  UK English identifier for generic programming language:
  <identifier lang="en-GB">Crotchet</identifier>
  
  English identifier for Python:
  <identifier lang="en-py">quarter_note</identifier>
  
  UK English identifier for Python:
  <identifier lang="en-GB-py">crotchet</identifier>

  Identifiers may not contain whitespace. Specific character rules for
  identifiers are programming-language dependent. For example, en:f may refer to
  forte and en:F may refer to the note letter F in a case-sensitive language.
  This would need to be overriden for a case-insensitive language such as
  Visual Basic, as perhaps en-vb:F and en-vb:Forte.
-->
<!ELEMENT identifier (#PCDATA)>
<!ATTLIST identifier
  lang CDATA #REQUIRED>

<!--
  The definition element provides the language-localized definition of a concept
  or category to be used in the context of documentation and reference.
  
  The lang attribute specifies the language-localization using a two-letter
  lowercase ISO 639-1 language code optionally followed by a hyphen and a
  two-letter uppercase ISO 3166-2 country code.
  
  The name attribute specifies the language-localized name of the concept
  according to the lang attribute.
  
  See the following examples.
  
  English definition:
  <definition lang="en" name="Quarter Note">A note of rhythm one-quarter shown
  by a filled in notehead and a stem with no flag</definition>

  UK English definition:
  <definition lang="en-GB" name="Crotchet">A note of rhythm one-quarter shown
  by a filled in notehead and a stem with no flag</definition>
-->
<!ELEMENT definition (#PCDATA)>
<!ATTLIST definition
  lang CDATA #REQUIRED
  name CDATA #REQUIRED
  xml:space (default | preserve) "default">

<!--
  The sequence element specifies that the concept refers to a sequence of other
  concepts. Inside the sequence tag is given a whitespace-separated list of
  language-localized concept identifiers.
  
  The cyclic attribute indicates that the sequence may be indexed modulo the
  length of the sequence by any integer. The default value to cyclic is false,
  thus it need only be expressed if it is being set to true.
  
  For example, within the Letters concept might be this sequence:
  <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
-->
  
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST sequence
  cyclic (true | false) "false">


<!--
  The following example shows all of the elements in this DTD being used in
  a hypothetical scenario declaring note letters and mapping the half and whole
  steps between adjacent letters.

  You can try validating the example at:
  http://validator.w3.org#validate_by_input
-->

<!--
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Letters">Group of concepts relating to note
      letters.</definition>
    
    <concept uuid="en:Letters">
      <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
      <identifier lang="en">Letters</identifier>
      <definition lang="en" name="Letters">Defines the cyclic sequence of
      note letters from A to G.</definition>
    </concept>
    
    <concept uuid="en:A"><identifier lang="en">A</identifier></concept>
    <concept uuid="en:B"><identifier lang="en">B</identifier></concept>
    <concept uuid="en:C"><identifier lang="en">C</identifier></concept>
    <concept uuid="en:D"><identifier lang="en">D</identifier></concept>
    <concept uuid="en:E"><identifier lang="en">E</identifier></concept>
    <concept uuid="en:F"><identifier lang="en">F</identifier></concept>
    <concept uuid="en:G"><identifier lang="en">G</identifier></concept>
  </category>
  
  <category>
    <definition lang="en" name="Steps">Group of concepts relating to note
      steps.</definition>
    
    <concept uuid="en:HalfStep">
      <identifier lang="en">HalfStep</identifier>
    </concept>
    
    <concept uuid="en:WholeStep">
      <identifier lang="en">WholeStep</identifier>
    </concept>
  </category>
  
  <map>en:A en:B en:WholeStep</map>
  <map>en:B en:C en:HalfStep</map>
  <map>en:C en:D en:WholeStep</map>
  <map>en:D en:E en:WholeStep</map>
  <map>en:E en:F en:HalfStep</map>
  <map>en:F en:G en:WholeStep</map>
  <map>en:G en:A en:WholeStep</map>
</mica>
-->

=== andigamesandmusic/belle/definitions/rhythm.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Rhythm">Contains basic rhythmic values.
    </definition>

    <concept uuid="en:Rest">
      <identifier lang="en">Rest</identifier>
      <definition lang="en" name="Rest">Denotes a durational rest.</definition>
    </concept>
    <concept uuid="en:MeasureRest">
      <identifier lang="en">MeasureRest</identifier>
      <definition lang="en" name="MeasureRest">Denotes a measure or multi-measure rest.</definition>
    </concept>
    <concept uuid="en:HundredTwentyEighthNote">
      <identifier lang="en">HundredTwentyEighthNote</identifier>
      <definition lang="en" name="Hundred Twenty-Eighth Note">Rhythmic value indicating one hundred twenty-eighth the duration of a whole note.</definition>
      <definition lang="en-GB" name="Semihemidemisemiquaver">Rhythmic value indicating one hundred twenty-eighth the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:SixtyFourthNote">
      <identifier lang="en">SixtyFourthNote</identifier>
      <definition lang="en" name="Sixty-Fourth Note">Rhythmic value indicating one sixty-fourth the duration of a whole note.</definition>
      <definition lang="en-GB" name="Hemidemisemiquaver">Rhythmic value indicating one sixty-fourth the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:ThirtySecondNote">
      <identifier lang="en">ThirtySecondNote</identifier>
      <definition lang="en" name="Thirty-Second Note">Rhythmic value indicating one thirty-second the duration of a whole note.</definition>
      <definition lang="en-GB" name="Demisemiquaver">Rhythmic value indicating one thirty-second the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:SixteenthNote">
      <identifier lang="en">SixteenthNote</identifier>
      <definition lang="en" name="Sixteenth Note">Rhythmic value indicating one sixteenth the duration of a whole note.</definition>
      <definition lang="en-GB" name="Semiquaver">Rhythmic value indicating one sixteenth the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:EighthNote">
      <identifier lang="en">EighthNote</identifier>
      <definition lang="en" name="Eighth Note">Rhythmic value indicating one eighth the duration of a whole note.</definition>
      <definition lang="en-GB" name="Quaver">Rhythmic value indicating one eighth the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:QuarterNote">
      <identifier lang="en">QuarterNote</identifier>
      <identifier lang="en-GB">Crotchet</identifier>
      <definition lang="en" name="Quarter Note">Rhythmic value indicating one quarter the duration of a whole note.</definition>
      <definition lang="en-GB-cpp" name="Crotchet">Rhythmic value indicating one quarter the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:HalfNote">
      <identifier lang="en">HalfNote</identifier>
      <definition lang="en" name="Half Note">Rhythmic value indicating one half the duration of a whole note.</definition>
      <definition lang="en-GB" name="Minim">Rhythmic value indicating one half the duration of a semibreve.</definition>
    </concept>
    <concept uuid="en:WholeNote">
      <identifier lang="en">WholeNote</identifier>
      <definition lang="en" name="Whole Note">Rhythmic value of length four beats in common time.</definition>
      <definition lang="en-GB" name="Semibreve">Rhythmic value of length four beats in common time.</definition>
    </concept>
    <concept uuid="en:DoubleWholeNote">
      <identifier lang="en">DoubleWholeNote</identifier>
      <definition lang="en" name="Double Whole Note">Rhythmic value indicating the duration of two whole notes.</definition>
      <definition lang="en-GB" name="Breve">Rhythmic value indicating the duration of two semibreves.</definition>
    </concept>
    <concept uuid="en:Longa">
      <identifier lang="en">Longa</identifier>
      <definition lang="en" name="Longa">Rhythmic value indicating the duration of four (or six) whole notes.</definition>
      <definition lang="en-GB" name="Longa">Rhythmic value indicating the duration of four (or six) semibreves.</definition>
    </concept>
    
  </category>
</mica>

=== andigamesandmusic/belle/definitions/visual.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Visual">Contains concepts relating to visual
    elements.</definition>
    
    <concept uuid="en:Symbol">
      <identifier lang="en">Symbol</identifier>
      <definition lang="en" name="Symbol">Used to specifically indicate the
      glyph-based aspect of another concept. For example, the Symbol to
      TrebleClef is GClef.</definition>
    </concept>

    <concept uuid="en:StaffPosition">
      <identifier lang="en">StaffPosition</identifier>
      <definition lang="en" name="Staff Position">An integer indicating the
      number of lines and/or spaces away from the middle line or space of a
      staff. An increment of one indicates the distance from a space to a
      neighboring line or a line to a neighboring space.</definition>
    </concept>
    
    <concept uuid="en:StemDirection">
      <identifier lang="en">StemDirection</identifier>
      <definition lang="en" name="Stem Direction">Represents a stem direction.
      </definition>
    </concept>
    
    <concept uuid="en:Up">
      <identifier lang="en">Up</identifier>
      <definition lang="en" name="Up">Represents the general notion of up.
      </definition>
    </concept>
    
    <concept uuid="en:Down">
      <identifier lang="en">Down</identifier>
      <definition lang="en" name="Down">Represents the general notion of down.
      </definition>
    </concept>
    
    <concept uuid="en:Beam">
      <identifier lang="en">Beam</identifier>
      <definition lang="en" name="Beam">Represents a rhythmic beam.</definition>
    </concept>
    
    <concept uuid="en:BeamDivision">
      <identifier lang="en">BeamDivision</identifier>
      <definition lang="en" name="Beam Division">Represents the ratio at which a beam is divided, such as 1/8, 1/16, etc.</definition>
    </concept>
    
    <concept uuid="en:AlternateDesign">
      <identifier lang="en">AlternateDesign</identifier>
      <definition lang="en" name="Alternate Design">Attribute of a token, in which an alternate visual design is desired. Many musical symbols have common alternate designs that are semantically identical, but visually
      distinct enough to be selected separately.</definition>
    </concept>
  </category>
</mica>

=== andigamesandmusic/belle/definitions/clef-symbols.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Clef Symbols">Contains clef symbols.
    </definition>

    <concept uuid="en:GClef">
      <identifier lang="en">GClef</identifier>
      <definition lang="en" name="G Clef">
      http://en.wikipedia.org/wiki/File:GClef.svg</definition>
    </concept>

    <concept uuid="en:GSuper8Clef">
      <identifier lang="en">GSuper8Clef</identifier>
      <definition lang="en" name="G Super 8 Clef">
      http://en.wikipedia.org/wiki/File:GClef.svg</definition>
    </concept>

    <concept uuid="en:GSuper15Clef">
      <identifier lang="en">GSuper15Clef</identifier>
      <definition lang="en" name="G Super 15 Clef">
      http://en.wikipedia.org/wiki/File:GClef.svg</definition>
    </concept>

    <concept uuid="en:FClef">
      <identifier lang="en">FClef</identifier>
      <definition lang="en" name="F Clef">
      http://en.wikipedia.org/wiki/File:FClef.svg</definition>
    </concept>

    <concept uuid="en:FSub8Clef">
      <identifier lang="en">FSub8Clef</identifier>
      <definition lang="en" name="F Sub 8 Clef">
      http://en.wikipedia.org/wiki/File:FClef.svg</definition>
    </concept>

    <concept uuid="en:FSub15Clef">
      <identifier lang="en">FSub15Clef</identifier>
      <definition lang="en" name="F Sub 15 Clef">
      http://en.wikipedia.org/wiki/File:FClef.svg</definition>
    </concept>

    <concept uuid="en:FSuper8Clef">
      <identifier lang="en">FSuper8Clef</identifier>
      <definition lang="en" name="F Super 8 Clef">
      http://en.wikipedia.org/wiki/File:FClef.svg</definition>
    </concept>

    <concept uuid="en:FSuper15Clef">
      <identifier lang="en">FSuper15Clef</identifier>
      <definition lang="en" name="F Super 15 Clef">
      http://en.wikipedia.org/wiki/File:FClef.svg</definition>
    </concept>

    <concept uuid="en:CClef">
      <identifier lang="en">CClef</identifier>
      <definition lang="en" name="C Clef">
      http://en.wikipedia.org/wiki/File:CClef.svg</definition>
    </concept>
    
    <concept uuid="en:BarredNeutralClef">
      <identifier lang="en">BarredNeutralClef</identifier>
      <definition lang="en" name="Barred Neutral Clef">
      http://en.wikipedia.org/wiki/File:Music-neutralclef.png</definition>
    </concept>
    
    <concept uuid="en:BoxedNeutralClef">
      <identifier lang="en">BoxedNeutralClef</identifier>
      <definition lang="en" name="Boxed Neutral Clef">
      http://en.wikipedia.org/wiki/File:Music-neutralclef.png</definition>
    </concept>
    
    <concept uuid="en:TABClef">
      <identifier lang="en">TABClef</identifier>
      <definition lang="en" name="TAB Clef">
      http://en.wikipedia.org/wiki/File:Tablature.svg</definition>
    </concept>
    
    <concept uuid="en:GregorianCClef">
      <identifier lang="en">GregorianCClef</identifier>
      <definition lang="en" name="Gregorian C Clef">
      http://en.wikipedia.org/wiki/File:C_clef_neume.gif</definition>
    </concept>
    
    <concept uuid="en:GregorianFClef">
      <identifier lang="en">GregorianFClef</identifier>
      <definition lang="en" name="Gregorian F Clef">
      http://en.wikipedia.org/wiki/File:F_clef_neume.gif</definition>
    </concept>
    
    <concept uuid="en:DoubleGClef">
      <identifier lang="en">DoubleGClef</identifier>
      <definition lang="en" name="Double G Clef">
      http://en.wikipedia.org/wiki/File:Tenorclefs.png</definition>
    </concept>
    
    <concept uuid="en:GSub8Clef">
      <identifier lang="en">GSub8Clef</identifier>
      <definition lang="en" name="G Sub 8 Clef">
      http://en.wikipedia.org/wiki/File:Tenorclefs.png</definition>
    </concept>

    <concept uuid="en:ReversedFClef">
      <identifier lang="en">ReversedFClef</identifier>
      <definition lang="en" name="Reversed F Clef">
      http://en.wikipedia.org/wiki/File:Oldbassclef.svg</definition>
    </concept>

    <concept uuid="en:BracketedCClef">
      <identifier lang="en">BracketedCClef</identifier>
      <definition lang="en" name="Bracketed C Clef">
      http://en.wikipedia.org/wiki/File:Old_C-clef.png</definition>
    </concept>

    <concept uuid="en:ParrallelogramCClef">
      <identifier lang="en">ParrallelogramCClef</identifier>
      <definition lang="en" name="Parrallelogram C Clef">
      http://en.wikipedia.org/wiki/File:Britannica_Horn_Nozze_C_Clef_Note_A.png
      </definition>
    </concept>

    <concept uuid="en:ScriptGClef">
      <identifier lang="en">ScriptGClef</identifier>
      <definition lang="en" name="Script G Clef">
      http://en.wikipedia.org/wiki/File:G-Schluessel.png</definition>
    </concept>

    <concept uuid="en:ScriptLittleGClef">
      <identifier lang="en">ScriptLittleGClef</identifier>
      <definition lang="en" name="Script Little G Clef">
      http://en.wikipedia.org/wiki/File:G-Schluessel.png</definition>
    </concept>

    <concept uuid="en:ScriptDGClef">
      <identifier lang="en">ScriptDGClef</identifier>
      <definition lang="en" name="Script D-G Clef">
      http://en.wikipedia.org/wiki/File:G-Schluessel.png</definition>
    </concept>

    <concept uuid="en:ScriptDGCombinedClef">
      <identifier lang="en">ScriptDGCombinedClef</identifier>
      <definition lang="en" name="Script D-G Combined Clef">
      http://en.wikipedia.org/wiki/File:G-Schluessel.png</definition>
    </concept>

  </category>
</mica>

=== andigamesandmusic/belle/definitions/barlines.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Barlines">Contains common barline types.
    </definition>
    
    <concept uuid="en:Barline">
      <identifier lang="en">Barline</identifier>
      <definition lang="en" name="Barline">Indicates a barline in the context of a measure or possibly intrameasure separator.</definition>
    </concept>
    
    <concept uuid="en:ThroughBarline">
      <identifier lang="en">ThroughBarline</identifier>
      <definition lang="en" name="Through Barline">Attribute of a barline in which it connects to the top of the staff immediately below.</definition>
    </concept>

    <concept uuid="en:StandardBarline">
      <identifier lang="en">StandardBarline</identifier>
      <definition lang="en" name="Standard Barline">Single thin vertical line through staff. If a through barline, line connects to top of next staff.</definition>
    </concept>

    <concept uuid="en:ThickBarline">
      <identifier lang="en">ThickBarline</identifier>
      <definition lang="en" name="Thick Barline">Thick vertical line through staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:ThinDoubleBarline">
      <identifier lang="en">ThinDoubleBarline</identifier>
      <definition lang="en" name="Thin Double Barline">Double thin vertical line through staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:ThickThinBarline">
      <identifier lang="en">ThickThinBarline</identifier>
      <definition lang="en" name="Thick-Thin Barline">Inverse of final barline through staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:ThickDoubleBarline">
      <identifier lang="en">ThickDoubleBarline</identifier>
      <definition lang="en" name="Thick Double Barline">Double thick vertical line through staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:ShortBarline">
      <identifier lang="en">ShortBarline</identifier>
      <definition lang="en" name="Short Barline">Two-space high line through middle of staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:TickBarline">
      <identifier lang="en">TickBarline</identifier>
      <definition lang="en" name="Tick Barline">Tick at top of staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:DottedBarline">
      <identifier lang="en">DottedBarline</identifier>
      <definition lang="en" name="Dotted Barline">Dashed vertical line through staff. If a through barline, line connects to top of next staff. In the alternate design, a dotted vertical line is used instead.</definition>
    </concept>
    
    <concept uuid="en:DashedBarline">
      <identifier lang="en">DashedBarline</identifier>
      <definition lang="en" name="Dashed Barline">Dashed vertical line through staff. If a through barline, line connects to top of next staff. In the alternate design, a dashed vertical line is used instead.</definition>
    </concept>

    <concept uuid="en:FinalBarline">
      <identifier lang="en">FinalBarline</identifier>
      <definition lang="en" name="Final Barline">Thin-thick line through staff. If a through barline, line connects to top of next staff.</definition>
    </concept>
    
    <concept uuid="en:EndRepeatBarline">
      <identifier lang="en">EndRepeatBarline</identifier>
      <definition lang="en" name="End Repeat Barline">Thin-thick line through staff with two dots to the left on the middle spaces. If a through barline, line connects to top of next staff.</definition>
    </concept>

    <concept uuid="en:BeginRepeatBarline">
      <identifier lang="en">BeginRepeatBarline</identifier>
      <definition lang="en" name="Begin Repeat Barline">Thick-thin line through staff with two dots to the right on the middle spaces. If a through barline, line connects to top of next staff.</definition>
    </concept>

    <concept uuid="en:BackToBackRepeatBarline">
      <identifier lang="en">BackToBackRepeatBarline</identifier>
      <definition lang="en" name="Back to Back Repeat Barline">Thin-thick-thin line with a pair of dots on each side. If a through barline, line connects to top of next staff. Indicates an end repeat barline and a begin repeat barline back to back. In the alternate design, a thick-thick line with a pair of dots on each side is used instead.</definition>
    </concept>
  </category>
</mica>

=== andigamesandmusic/belle/definitions/modes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Modes">Contains modes.</definition>
    
    <concept uuid="en:Mode">
      <identifier lang="en">Mode</identifier>
      <definition lang="en" name="Mode">Represents the concept of a
      mode.</definition>
    </concept>

    <!--en:Major and en:Minor defined homonymously in IntervalAspects.xml-->

    <concept uuid="en:Ionian">
      <identifier lang="en">Ionian</identifier>
      <definition lang="en" name="Ionian">Represents the concept of the
      Ionian mode.</definition>
    </concept>
    <concept uuid="en:Dorian">
      <identifier lang="en">Dorian</identifier>
      <definition lang="en" name="Dorian">Represents the concept of the
      Dorian mode.</definition>
    </concept>
    <concept uuid="en:Phrygian">
      <identifier lang="en">Phrygian</identifier>
      <definition lang="en" name="Phrygian">Represents the concept of the
      Phrygian mode.</definition>
    </concept>
    <concept uuid="en:Lydian">
      <identifier lang="en">Lydian</identifier>
      <definition lang="en" name="Lydian">Represents the concept of the
      Lydian mode.</definition>
    </concept>
    <concept uuid="en:Mixolydian">
      <identifier lang="en">Mixolydian</identifier>
      <definition lang="en" name="Mixolydian">Represents the concept of the
      Mixolydian mode.</definition>
    </concept>
    <concept uuid="en:Aeolian">
      <identifier lang="en">Aeolian</identifier>
      <definition lang="en" name="Aeolian">Represents the concept of the
      Aeolian mode.</definition>
    </concept>
    <concept uuid="en:Locrian">
      <identifier lang="en">Locrian</identifier>
      <definition lang="en" name="Locrian">Represents the concept of the
      Locrian mode.</definition>
    </concept>
  </category>
</mica>
