=== andigamesandmusic/belle/definitions/mica.dtd
<!--
  MICA (Music Information Concept Archive) DTD
  
  Version 1.0
  
  Copyright 2007-2013, 2017 Andi

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
-->

<!--
  The mica element may contain mappings and/or concept categories. A single
  mica XML file may thus describe a portion or all of the MICA dictionary.
  
	Suggested use:
	
	<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<!DOCTYPE mica PUBLIC
		"-//MICA//DTD Music Information Concept Archive//EN"
		"https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
-->

<!--
  The mica element may contain zero or more map and category elements. It has
  no attributes.
-->
<!ELEMENT mica (map | category)*>

<!--
  The map element contains a whitespace-separated list of language-localized
  identifiers. The mapping uses all but the last identifier as the input
  multiset and the last identifier as the output.
  
  Example:
  <map>en:A en:B en:C</map>           means {en:A en:B} -> en:C
  
  Note that the input is unordered. Therefore the following is equivalent:
  <map>en:B en:A en:C</map>      also means {en:A en:B} -> en:C
  
  The language-localized identifier must refer to an identifier element found
  elsewhere in the MICA dictionary (potentially in another XML file).
  
  For example, en:A refers to the concept containing the identifier tag:
  <identifier lang="en">A</identifier>
-->
<!ELEMENT map (#PCDATA)>

<!--
  The category element contains one or more definition and concept elements.
  
  A definition element is provided for each language-localization of the
  category name and definition. Categories are semantic groups used primarily
  for organization and documentation. They are not necessarily encoded in the
  programming language APIs.
  
  A concept element is provided to declare a concept that belongs to the given
  category.
  
  The contents of a category element may not be partially specified. All
  concepts and definitions relevant to the category must be contained in one
  tag (a single category may not spread across multiple files).
-->
<!ELEMENT category (definition | concept)+>

<!--
  The concept element contains an optional sequence element (if it represents a
  sequence) followed by one or more (programming language) identifier elements
  followed by zero or more (natural language) definition elements.
  
  The uuid attribute specifies either one of the language-localized identifiers
  specified within the concept (for example, en:QuarterNote) or a UUID in the
  canonical hex format:
  
  nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn
  
  Where n is a digit 0-9 or lowercase letter a-f. Uppercase letters must not
  be used (the UUID must be expressed in canonical lowercase form).
  
  Note that if a language-localized identifier is used, it is internally
  converted to a UUID via the MD5 namespace algorithm. The identifier thus
  uniquely maps to a UUID.
  
  ATTENTION:
  
  THE uuid ATTRIBUTE MUST NOT BE CHANGED TO ANOTHER IDENTIFIER AFTER IT IS SET.
  CHANGING THE uuid IDENTIFIER CHANGES THE UNDERLYING UUID ENCODING AND WILL
  REDEFINE THE CONCEPT TO A DIFFERENT NUMBER.
  
  In cases where the identifier must be changed, an error will be emitted during
  the parse if the identifier no longer exists and the uuid attribute must then
  be changed to use an explicit UUID representing the original UUID.
  Backwards-compatibility is a requirement of MICA. In these cases a comment
  should also be provided indicating the source of the original UUID.
-->

<!ELEMENT concept (sequence?, identifier+, definition*)>
<!ATTLIST concept
  uuid CDATA #REQUIRED>

<!--
  The identifier element provides the programming and natural language-localized
  identifier name of a concept to be used in the context of a programming
  language.
  
  The lang attribute specifies the language-localization using a two-letter
  lowercase ISO 639-1 language code optionally followed by a hyphen and a
  two-letter uppercase ISO 3166-2 country code optionally followed by a hyphen
  and the commonly accepted extension of a source code file in the target
  programming language.
  
  See the following examples.
  
  English identifier for generic programming language:  
  <identifier lang="en">QuarterNote</identifier>
  
  UK English identifier for generic programming language:
  <identifier lang="en-GB">Crotchet</identifier>
  
  English identifier for Python:
  <identifier lang="en-py">quarter_note</identifier>
  
  UK English identifier for Python:
  <identifier lang="en-GB-py">crotchet</identifier>

  Identifiers may not contain whitespace. Specific character rules for
  identifiers are programming-language dependent. For example, en:f may refer to
  forte and en:F may refer to the note letter F in a case-sensitive language.
  This would need to be overriden for a case-insensitive language such as
  Visual Basic, as perhaps en-vb:F and en-vb:Forte.
-->
<!ELEMENT identifier (#PCDATA)>
<!ATTLIST identifier
  lang CDATA #REQUIRED>

<!--
  The definition element provides the language-localized definition of a concept
  or category to be used in the context of documentation and reference.
  
  The lang attribute specifies the language-localization using a two-letter
  lowercase ISO 639-1 language code optionally followed by a hyphen and a
  two-letter uppercase ISO 3166-2 country code.
  
  The name attribute specifies the language-localized name of the concept
  according to the lang attribute.
  
  See the following examples.
  
  English definition:
  <definition lang="en" name="Quarter Note">A note of rhythm one-quarter shown
  by a filled in notehead and a stem with no flag</definition>

  UK English definition:
  <definition lang="en-GB" name="Crotchet">A note of rhythm one-quarter shown
  by a filled in notehead and a stem with no flag</definition>
-->
<!ELEMENT definition (#PCDATA)>
<!ATTLIST definition
  lang CDATA #REQUIRED
  name CDATA #REQUIRED
  xml:space (default | preserve) "default">

<!--
  The sequence element specifies that the concept refers to a sequence of other
  concepts. Inside the sequence tag is given a whitespace-separated list of
  language-localized concept identifiers.
  
  The cyclic attribute indicates that the sequence may be indexed modulo the
  length of the sequence by any integer. The default value to cyclic is false,
  thus it need only be expressed if it is being set to true.
  
  For example, within the Letters concept might be this sequence:
  <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
-->
  
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST sequence
  cyclic (true | false) "false">


<!--
  The following example shows all of the elements in this DTD being used in
  a hypothetical scenario declaring note letters and mapping the half and whole
  steps between adjacent letters.

  You can try validating the example at:
  http://validator.w3.org#validate_by_input
-->

<!--
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Letters">Group of concepts relating to note
      letters.</definition>
    
    <concept uuid="en:Letters">
      <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
      <identifier lang="en">Letters</identifier>
      <definition lang="en" name="Letters">Defines the cyclic sequence of
      note letters from A to G.</definition>
    </concept>
    
    <concept uuid="en:A"><identifier lang="en">A</identifier></concept>
    <concept uuid="en:B"><identifier lang="en">B</identifier></concept>
    <concept uuid="en:C"><identifier lang="en">C</identifier></concept>
    <concept uuid="en:D"><identifier lang="en">D</identifier></concept>
    <concept uuid="en:E"><identifier lang="en">E</identifier></concept>
    <concept uuid="en:F"><identifier lang="en">F</identifier></concept>
    <concept uuid="en:G"><identifier lang="en">G</identifier></concept>
  </category>
  
  <category>
    <definition lang="en" name="Steps">Group of concepts relating to note
      steps.</definition>
    
    <concept uuid="en:HalfStep">
      <identifier lang="en">HalfStep</identifier>
    </concept>
    
    <concept uuid="en:WholeStep">
      <identifier lang="en">WholeStep</identifier>
    </concept>
  </category>
  
  <map>en:A en:B en:WholeStep</map>
  <map>en:B en:C en:HalfStep</map>
  <map>en:C en:D en:WholeStep</map>
  <map>en:D en:E en:WholeStep</map>
  <map>en:E en:F en:HalfStep</map>
  <map>en:F en:G en:WholeStep</map>
  <map>en:G en:A en:WholeStep</map>
</mica>
-->

=== andigamesandmusic/belle/definitions/staff.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Staff">Definitions for staff objects.
    </definition>
    <concept uuid="en:StaffBracket">
      <identifier lang="en">StaffBracket</identifier>
      <definition lang="en" name="Staff Bracket">A bracket used to group staves of instruments together.</definition>
    </concept>
    
    <concept uuid="en:Brace">
      <identifier lang="en">Brace</identifier>
      <definition lang="en" name="Brace">A curly-bracket used to group adjacent
      staves into a part.</definition>
    </concept>
    
    <concept uuid="en:SquareBracket">
      <identifier lang="en">SquareBracket</identifier>
      <definition lang="en" name="Square Bracket">A square bracket with curved
      ends used to join sections of instruments.</definition>
    </concept>
    
    <concept uuid="en:ThinSquareBracket">
      <identifier lang="en">ThinSquareBracket</identifier>
      <definition lang="en" name="Thin Square Bracket">A thin square bracket used as a secondary grouping for a section of instruments.</definition>
    </concept>
  </category>
</mica>

=== andigamesandmusic/belle/definitions/meter.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Meter">Contains meter concepts.</definition>
    
    <concept uuid="en:SimpleMeter">
      <identifier lang="en">SimpleMeter</identifier>
      <definition lang="en" name="Simple Meter">Indicates a simple meter which uses an undotted note for its beat.</definition>
    </concept>

    <concept uuid="en:CompoundMeter">
      <identifier lang="en">CompoundMeter</identifier>
      <definition lang="en" name="Compound Meter">Indicates a compound meter which uses an dotted note for its beat.</definition>
    </concept>

    <concept uuid="en:ComplexMeter">
      <identifier lang="en">ComplexMeter</identifier>
      <definition lang="en" name="Complex Meter">Indicates a meter which divides into uneven parts.</definition>
    </concept>

    <concept uuid="en:IrrationalMeter">
      <identifier lang="en">IrrationalMeter</identifier>
      <definition lang="en" name="Irrational Meter">Indicates a meter which has a denominator that is not a power of two such as 4 over 5.</definition>
    </concept>

  </category>
</mica>

=== andigamesandmusic/belle/definitions/accidentals.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Accidentals">Contains common accidentals.
    </definition>

    <concept uuid="en:TripleFlat">
      <identifier lang="en">TripleFlat</identifier>
      <definition lang="en" name="Triple flat">Indicates a relative lowering of
      pitch by three semitones.</definition>
    </concept>

    <concept uuid="en:DoubleFlat">
      <identifier lang="en">DoubleFlat</identifier>
      <definition lang="en" name="Double flat">Indicates a relative lowering of
      pitch by two semitones.</definition>
    </concept>
    
    <concept uuid="en:FlatAndAHalf">
      <identifier lang="en">FlatAndAHalf</identifier>
      <definition lang="en" name="Flat-and-a-half">Indicates a relative lowering of pitch by one and a half semitones.</definition>
    </concept>

    <concept uuid="en:Flat">
      <identifier lang="en">Flat</identifier>
      <definition lang="en" name="Flat">Indicates a relative lowering of
      pitch by one semitone.</definition>
    </concept>
    
    <concept uuid="en:HalfFlat">
      <identifier lang="en">HalfFlat</identifier>
      <definition lang="en" name="Half Flat">Indicates a relative lowering of pitch by a half a semitone.</definition>
    </concept>

    <concept uuid="en:Natural">
      <identifier lang="en">Natural</identifier>
      <definition lang="en" name="Natural">Indicates that the pitch given is not
      raised or lowered.</definition>
    </concept>
    
    <concept uuid="en:HalfSharp">
      <identifier lang="en">HalfSharp</identifier>
      <definition lang="en" name="Half Sharp">Indicates a relative raising of pitch by a half a semitone.</definition>
    </concept>

    <concept uuid="en:Sharp">
      <identifier lang="en">Sharp</identifier>
      <definition lang="en" name="Sharp">Indicates a relative raising of
      pitch by one semitone.</definition>
    </concept>
    
    <concept uuid="en:SharpAndAHalf">
      <identifier lang="en">SharpAndAHalf</identifier>
      <definition lang="en" name="Sharp-and-a-half">Indicates a relative raising of pitch by one and a half semitones.</definition>
    </concept>

    <concept uuid="en:DoubleSharp">
      <identifier lang="en">DoubleSharp</identifier>
      <definition lang="en" name="Double sharp">Indicates a relative raising of
      pitch by two semitones.</definition>
    </concept>

    <concept uuid="en:TripleSharp">
      <identifier lang="en">TripleSharp</identifier>
      <definition lang="en" name="Triple sharp">Indicates a relative raising of
      pitch by three semitones.</definition>
    </concept>

    <concept uuid="en:Accidentals">
      <sequence>en:TripleFlat en:DoubleFlat en:Flat en:Natural en:Sharp
      en:DoubleSharp en:TripleSharp</sequence>
      <identifier lang="en">Accidentals</identifier>
      <definition lang="en" name="Accidentals">Sequence of common diatonic
      accidentals from most flat to most sharp.</definition>
    </concept>
    
  </category>
</mica>

=== andigamesandmusic/belle/definitions/time-signatures.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Time Signatures">Contains time signature types.
    </definition>

    <concept uuid="en:Beats">
      <identifier lang="en">Beats</identifier>
      <definition lang="en" name="Beats">Indicates the number of beats in a
        measure.</definition>
    </concept>

    <concept uuid="en:NoteValue">
      <identifier lang="en">NoteValue</identifier>
      <definition lang="en" name="Note Value">Indicates a note value.</definition>
    </concept>
    
    <concept uuid="en:CommonTime">
      <identifier lang="en">CommonTime</identifier>
      <definition lang="en" name="Common Time">Indicates a styled c normally taken to mean a time signature of 4/4.</definition>
    </concept>

    <concept uuid="en:CutTime">
      <identifier lang="en">CutTime</identifier>
      <definition lang="en" name="Cut Time">Indicates a styled c with vertical stroke normally taken to mean a time signature of 2/2.</definition>
    </concept>

    <concept uuid="en:RegularTimeSignature">
      <identifier lang="en">RegularTimeSignature</identifier>
      <definition lang="en" name="Regular Time Signature">Indicates a time signature expressed as a whole numerator over a whole denominator such as 6 over 8.</definition>
    </concept>
    
    <concept uuid="en:OpenTimeSignature">
      <identifier lang="en">OpenTimeSignature</identifier>
      <definition lang="en" name="Open Time Signature">Indicates an open time signature (i.e. senza misura).</definition>
    </concept>
    
    <concept uuid="en:SingleNumberTimeSignature">
      <identifier lang="en">SingleNumberTimeSignature</identifier>
      <definition lang="en" name="Single Number Time Signature">Indicates a time signature expressed with a single number numerator and no denominator.</definition>
    </concept>

    <concept uuid="en:AdditiveTimeSignature">
      <identifier lang="en">AdditiveTimeSignature</identifier>
      <definition lang="en" name="Additive Time Signature">Indicates a time signature expressed as a sum of whole numbers for the numerator over a whole denominator such as 3+2+3 over 8.</definition>
    </concept>

    <concept uuid="en:FractionalTimeSignature">
      <identifier lang="en">FractionalTimeSignature</identifier>
      <definition lang="en" name="Fractional Time Signature">Indicates a time signature expressed as a fractional number for the numerator over a whole denominator such as 3 1/2 over 8.</definition>
    </concept>

  </category>
</mica>

=== andigamesandmusic/belle/definitions/structure.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Structure">Contains structural score elements.
    </definition>
    <concept uuid="en:Partwise">
      <identifier lang="en">Partwise</identifier>
      <definition lang="en" name="Partwise">Along a musical part (horizontally
        across a score). Partwise links serialize horizontal elements.</definition>
    </concept>
    <concept uuid="en:Instantwise">
      <identifier lang="en">Instantwise</identifier>
      <definition lang="en" name="Instant-wise">Along a musical instant
        (vertically down a score). Instant-wise links connect elements between parts that are vertically simultaneous.</definition>
    </concept>
    <concept uuid="en:Type">
      <identifier lang="en">Type</identifier>
      <definition lang="en" name="Type">Indicates the type of something.</definition>
    </concept>
    <concept uuid="en:Kind">
      <identifier lang="en">Kind</identifier>
      <definition lang="en" name="Kind">Indicates the kind of a typed thing.</definition>
    </concept>
    <concept uuid="en:Value">
      <identifier lang="en">Value</identifier>
      <definition lang="en" name="Value">Indicates the value of a thing.</definition>
    </concept>
    <concept uuid="en:Node">
      <identifier lang="en">Node</identifier>
      <definition lang="en" name="Node">Indicates a node.</definition>
    </concept>    
    <concept uuid="en:Island">
      <identifier lang="en">Island</identifier>
      <definition lang="en" name="Island">Indicates a music graph island.</definition>
    </concept>
    <concept uuid="en:Token">
      <identifier lang="en">Token</identifier>
      <definition lang="en" name="Token">Indicates a music graph token.</definition>
    </concept>
    <concept uuid="en:Note">
      <identifier lang="en">Note</identifier>
      <definition lang="en" name="Note">Indicates a music graph note.</definition>
    </concept>
    <concept uuid="en:Marking">
      <identifier lang="en">Marking</identifier>
      <definition lang="en" name="Marking">Indicates a music graph marking.</definition>
    </concept>
    <concept uuid="en:Float">
      <identifier lang="en">Float</identifier>
      <definition lang="en" name="Float">Indicates a music graph float.</definition>
    </concept>
    <concept uuid="en:Span">
      <identifier lang="en">Span</identifier>
      <definition lang="en" name="Span">Indicates a span designated by a link.</definition>
    </concept>
    <concept uuid="en:Property">
      <identifier lang="en">Property</identifier>
      <definition lang="en" name="Property">Indicates a music graph property.</definition>
    </concept>
    <concept uuid="en:Metadata">
      <identifier lang="en">Metadata</identifier>
      <definition lang="en" name="Metadata">Indicates music graph metadata.</definition>
    </concept>
    <concept uuid="en:Tuplet">
      <identifier lang="en">Tuplet</identifier>
      <definition lang="en" name="Tuplet">Indicates a tuplet edge or node.</definition>
    </concept>
    <concept uuid="en:FullRatio">
      <identifier lang="en">FullRatio</identifier>
      <definition lang="en" name="Full Ratio">Indicates that tuplet should show its full ratio.</definition>
    </concept>
    
    <concept uuid="en:AnnotationTree">
      <identifier lang="en">AnnotationTree</identifier>
      <definition lang="en" name="Annotation Tree">
        Denotes an annotation tree node or link for a system.
      </definition>
    </concept>
    <concept uuid="en:Annotation">
      <identifier lang="en">Annotation</identifier>
      <definition lang="en" name="Annotation">
        Denotes an annotation node or link.
      </definition>
    </concept>
    <!--
      Barline in Barlines
    -->
    <concept uuid="en:Chord">
      <identifier lang="en">Chord</identifier>
      <definition lang="en" name="Chord">Indicates a music graph chord.</definition>
    </concept>
    <concept uuid="en:Clef">
      <identifier lang="en">Clef</identifier>
      <definition lang="en" name="Clef">Indicates a music graph clef.</definition>
    </concept>
    <!--
      KeySignature in KeySignatures
    -->
    <concept uuid="en:TimeSignature">
      <identifier lang="en">TimeSignature</identifier>
      <definition lang="en" name="Time Signature">Indicates a music graph time signature.</definition>
    </concept>
    <concept uuid="en:Analysis">
      <identifier lang="en">Analysis</identifier>
      <definition lang="en" name="Analysis">Indicates a music graph analysis.</definition>
    </concept>
    <concept uuid="en:Mark">
      <identifier lang="en">Mark</identifier>
      <definition lang="en" name="Mark">Indicates a music graph mark.</definition>
    </concept>
    <concept uuid="en:Tie">
      <identifier lang="en">Tie</identifier>
      <definition lang="en" name="Tie">Indicates a music graph tie.</definition>
    </concept>
    <concept uuid="en:PartialTieIncoming">
      <identifier lang="en">PartialTieIncoming</identifier>
      <definition lang="en" name="Partial Tie Incoming">Indicates a music graph tie, usually at the beginning of a system, that hangs to the left of the note without attaching to a previous note indicating that it is tied to a note on the previous system.</definition>
    </concept>
    <concept uuid="en:PartialTieOutgoing">
      <identifier lang="en">PartialTieOutgoing</identifier>
      <definition lang="en" name="Partial Tie Outgoing">Indicates a music graph tie, usually at the end of a system, that hangs to the right of the note without attaching to a next note indicating that it is tied to a note on the following system.</definition>
    </concept>
    <concept uuid="en:Slur">
      <identifier lang="en">Slur</identifier>
      <definition lang="en" name="Slur">Indicates a music graph slur.
      </definition>
    </concept>
    <concept uuid="en:Articulation">
      <identifier lang="en">Articulation</identifier>
      <definition lang="en" name="Articulation">Indicates a music graph articulation.</definition>
    </concept>
    <concept uuid="en:Continuity">
      <identifier lang="en">Continuity</identifier>
      <definition lang="en" name="Continuity">Indicates a music graph continuity.</definition>
    </concept>
    <concept uuid="en:Voice">
      <identifier lang="en">Voice</identifier>
      <definition lang="en" name="Voice">Indicates a music graph voice.</definition>
    </concept>
    <concept uuid="en:Expression">
      <identifier lang="en">Expression</identifier>
      <definition lang="en" name="Expression">Indicates an expression mark such as a dynamic or italicized text.</definition>
    </concept>
    <concept uuid="en:OctaveTransposition">
      <identifier lang="en">OctaveTransposition</identifier>
      <definition lang="en" name="Octave Transposition">Indicates an octave-transposition line.</definition>
    </concept>
    <concept uuid="en:Placement">
      <identifier lang="en">Placement</identifier>
      <definition lang="en" name="Placement">Indicates the placement of something.</definition>
    </concept>
    <concept uuid="en:PedalMarking">
      <identifier lang="en">PedalMarking</identifier>
      <definition lang="en" name="Pedal Marking">Indicates a pedal marking.</definition>
    </concept>
    <concept uuid="en:DamperPedal">
      <identifier lang="en">DamperPedal</identifier>
      <definition lang="en" name="Damper Pedal">Indicates a damper pedal marking.</definition>
    </concept>
    <concept uuid="en:SostenutoPedal">
      <identifier lang="en">SostenutoPedal</identifier>
      <definition lang="en" name="Sostenuto Pedal">Indicates a sostenuto pedal marking.</definition>
    </concept>
    <concept uuid="en:UnaCordaPedal">
      <identifier lang="en">UnaCordaPedal</identifier>
      <definition lang="en" name="Una Corda Pedal">Indicates a una corda pedal marking.</definition>
    </concept>
    <concept uuid="en:PedalRelease">
      <identifier lang="en">PedalRelease</identifier>
      <definition lang="en" name="Pedal Release">Indicates a pedal release marking.</definition>
    </concept>
    <concept uuid="en:DamperPedalRelease">
      <identifier lang="en">DamperPedalRelease</identifier>
      <definition lang="en" name="Damper Pedal Release">Indicates a damper pedal release marking.</definition>
    </concept>
    <concept uuid="en:PedalRetake">
      <identifier lang="en">PedalRetake</identifier>
      <definition lang="en" name="Pedal Retake">Indicates a brief pedal up and back down.</definition>
    </concept>
    <concept uuid="en:SystemBreak">
      <identifier lang="en">SystemBreak</identifier>
      <definition lang="en" name="System Break">Indicates a mandantory system break.</definition>
    </concept>
    <concept uuid="en:OptionalBreak">
      <identifier lang="en">OptionalBreak</identifier>
      <definition lang="en" name="Optional Break">Indicates an optional system break as determined by the typesetter.</definition>
    </concept>
    <concept uuid="en:RepeatingInstant">
      <identifier lang="en">RepeatingInstant</identifier>
      <definition lang="en" name="Repeating Instant">Indicates an instant that repeats its glyph across a system break. An example of this would be a clef which repeats at the beginning of each system.</definition>
     </concept>
    <concept uuid="en:AbsorbedInstant">
      <identifier lang="en">AbsorbedInstant</identifier>
      <definition lang="en" name="Absorbed Instant">Indicates that an instant is absorbed by a system break. That is it appears normally if the system is not breaking, but if it immediately follows a system break, then the contents of the instant are absorbed into existing repeating instants.</definition>
    </concept>
  </category>
</mica>
