=== andigamesandmusic/belle/definitions/mica.dtd
<!--
  MICA (Music Information Concept Archive) DTD
  
  Version 1.0
  
  Copyright 2007-2013, 2017 Andi

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
-->

<!--
  The mica element may contain mappings and/or concept categories. A single
  mica XML file may thus describe a portion or all of the MICA dictionary.
  
	Suggested use:
	
	<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<!DOCTYPE mica PUBLIC
		"-//MICA//DTD Music Information Concept Archive//EN"
		"https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
-->

<!--
  The mica element may contain zero or more map and category elements. It has
  no attributes.
-->
<!ELEMENT mica (map | category)*>

<!--
  The map element contains a whitespace-separated list of language-localized
  identifiers. The mapping uses all but the last identifier as the input
  multiset and the last identifier as the output.
  
  Example:
  <map>en:A en:B en:C</map>           means {en:A en:B} -> en:C
  
  Note that the input is unordered. Therefore the following is equivalent:
  <map>en:B en:A en:C</map>      also means {en:A en:B} -> en:C
  
  The language-localized identifier must refer to an identifier element found
  elsewhere in the MICA dictionary (potentially in another XML file).
  
  For example, en:A refers to the concept containing the identifier tag:
  <identifier lang="en">A</identifier>
-->
<!ELEMENT map (#PCDATA)>

<!--
  The category element contains one or more definition and concept elements.
  
  A definition element is provided for each language-localization of the
  category name and definition. Categories are semantic groups used primarily
  for organization and documentation. They are not necessarily encoded in the
  programming language APIs.
  
  A concept element is provided to declare a concept that belongs to the given
  category.
  
  The contents of a category element may not be partially specified. All
  concepts and definitions relevant to the category must be contained in one
  tag (a single category may not spread across multiple files).
-->
<!ELEMENT category (definition | concept)+>

<!--
  The concept element contains an optional sequence element (if it represents a
  sequence) followed by one or more (programming language) identifier elements
  followed by zero or more (natural language) definition elements.
  
  The uuid attribute specifies either one of the language-localized identifiers
  specified within the concept (for example, en:QuarterNote) or a UUID in the
  canonical hex format:
  
  nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn
  
  Where n is a digit 0-9 or lowercase letter a-f. Uppercase letters must not
  be used (the UUID must be expressed in canonical lowercase form).
  
  Note that if a language-localized identifier is used, it is internally
  converted to a UUID via the MD5 namespace algorithm. The identifier thus
  uniquely maps to a UUID.
  
  ATTENTION:
  
  THE uuid ATTRIBUTE MUST NOT BE CHANGED TO ANOTHER IDENTIFIER AFTER IT IS SET.
  CHANGING THE uuid IDENTIFIER CHANGES THE UNDERLYING UUID ENCODING AND WILL
  REDEFINE THE CONCEPT TO A DIFFERENT NUMBER.
  
  In cases where the identifier must be changed, an error will be emitted during
  the parse if the identifier no longer exists and the uuid attribute must then
  be changed to use an explicit UUID representing the original UUID.
  Backwards-compatibility is a requirement of MICA. In these cases a comment
  should also be provided indicating the source of the original UUID.
-->

<!ELEMENT concept (sequence?, identifier+, definition*)>
<!ATTLIST concept
  uuid CDATA #REQUIRED>

<!--
  The identifier element provides the programming and natural language-localized
  identifier name of a concept to be used in the context of a programming
  language.
  
  The lang attribute specifies the language-localization using a two-letter
  lowercase ISO 639-1 language code optionally followed by a hyphen and a
  two-letter uppercase ISO 3166-2 country code optionally followed by a hyphen
  and the commonly accepted extension of a source code file in the target
  programming language.
  
  See the following examples.
  
  English identifier for generic programming language:  
  <identifier lang="en">QuarterNote</identifier>
  
  UK English identifier for generic programming language:
  <identifier lang="en-GB">Crotchet</identifier>
  
  English identifier for Python:
  <identifier lang="en-py">quarter_note</identifier>
  
  UK English identifier for Python:
  <identifier lang="en-GB-py">crotchet</identifier>

  Identifiers may not contain whitespace. Specific character rules for
  identifiers are programming-language dependent. For example, en:f may refer to
  forte and en:F may refer to the note letter F in a case-sensitive language.
  This would need to be overriden for a case-insensitive language such as
  Visual Basic, as perhaps en-vb:F and en-vb:Forte.
-->
<!ELEMENT identifier (#PCDATA)>
<!ATTLIST identifier
  lang CDATA #REQUIRED>

<!--
  The definition element provides the language-localized definition of a concept
  or category to be used in the context of documentation and reference.
  
  The lang attribute specifies the language-localization using a two-letter
  lowercase ISO 639-1 language code optionally followed by a hyphen and a
  two-letter uppercase ISO 3166-2 country code.
  
  The name attribute specifies the language-localized name of the concept
  according to the lang attribute.
  
  See the following examples.
  
  English definition:
  <definition lang="en" name="Quarter Note">A note of rhythm one-quarter shown
  by a filled in notehead and a stem with no flag</definition>

  UK English definition:
  <definition lang="en-GB" name="Crotchet">A note of rhythm one-quarter shown
  by a filled in notehead and a stem with no flag</definition>
-->
<!ELEMENT definition (#PCDATA)>
<!ATTLIST definition
  lang CDATA #REQUIRED
  name CDATA #REQUIRED
  xml:space (default | preserve) "default">

<!--
  The sequence element specifies that the concept refers to a sequence of other
  concepts. Inside the sequence tag is given a whitespace-separated list of
  language-localized concept identifiers.
  
  The cyclic attribute indicates that the sequence may be indexed modulo the
  length of the sequence by any integer. The default value to cyclic is false,
  thus it need only be expressed if it is being set to true.
  
  For example, within the Letters concept might be this sequence:
  <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
-->
  
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST sequence
  cyclic (true | false) "false">


<!--
  The following example shows all of the elements in this DTD being used in
  a hypothetical scenario declaring note letters and mapping the half and whole
  steps between adjacent letters.

  You can try validating the example at:
  http://validator.w3.org#validate_by_input
-->

<!--
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Letters">Group of concepts relating to note
      letters.</definition>
    
    <concept uuid="en:Letters">
      <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
      <identifier lang="en">Letters</identifier>
      <definition lang="en" name="Letters">Defines the cyclic sequence of
      note letters from A to G.</definition>
    </concept>
    
    <concept uuid="en:A"><identifier lang="en">A</identifier></concept>
    <concept uuid="en:B"><identifier lang="en">B</identifier></concept>
    <concept uuid="en:C"><identifier lang="en">C</identifier></concept>
    <concept uuid="en:D"><identifier lang="en">D</identifier></concept>
    <concept uuid="en:E"><identifier lang="en">E</identifier></concept>
    <concept uuid="en:F"><identifier lang="en">F</identifier></concept>
    <concept uuid="en:G"><identifier lang="en">G</identifier></concept>
  </category>
  
  <category>
    <definition lang="en" name="Steps">Group of concepts relating to note
      steps.</definition>
    
    <concept uuid="en:HalfStep">
      <identifier lang="en">HalfStep</identifier>
    </concept>
    
    <concept uuid="en:WholeStep">
      <identifier lang="en">WholeStep</identifier>
    </concept>
  </category>
  
  <map>en:A en:B en:WholeStep</map>
  <map>en:B en:C en:HalfStep</map>
  <map>en:C en:D en:WholeStep</map>
  <map>en:D en:E en:WholeStep</map>
  <map>en:E en:F en:HalfStep</map>
  <map>en:F en:G en:WholeStep</map>
  <map>en:G en:A en:WholeStep</map>
</mica>
-->

=== andigamesandmusic/belle/definitions/chromatic-notes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Chromatic Notes">Contains note names that are
    modified by accidentals.</definition>

    <concept uuid="en:ATripleFlat">
      <identifier lang="en">ATripleFlat</identifier>
      <definition lang="en" name="A triple-flat">Represents the pitch class A
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:ADoubleFlat">
      <identifier lang="en">ADoubleFlat</identifier>
      <definition lang="en" name="A double-flat">Represents the pitch class A
      lowered by a double flat.</definition></concept>
    <concept uuid="en:AFlat">
      <identifier lang="en">AFlat</identifier>
      <definition lang="en" name="A flat">Represents the pitch class A
      lowered by a flat.</definition></concept>
    <concept uuid="en:ASharp">
      <identifier lang="en">ASharp</identifier>
      <definition lang="en" name="A sharp">Represents the pitch class A
      raised by a sharp.</definition></concept>
    <concept uuid="en:ADoubleSharp">
      <identifier lang="en">ADoubleSharp</identifier>
      <definition lang="en" name="A double-sharp">Represents the pitch class A
      raised by a double sharp.</definition></concept>
    <concept uuid="en:ATripleSharp">
      <identifier lang="en">ATripleSharp</identifier>
      <definition lang="en" name="A triple-sharp">Represents the pitch class A
      raised by a triple sharp.</definition></concept>

    <concept uuid="en:BTripleFlat">
      <identifier lang="en">BTripleFlat</identifier>
      <definition lang="en" name="B triple-flat">Represents the pitch class B
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:BDoubleFlat">
      <identifier lang="en">BDoubleFlat</identifier>
      <definition lang="en" name="B double-flat">Represents the pitch class B
      lowered by a double flat.</definition></concept>
    <concept uuid="en:BFlat">
      <identifier lang="en">BFlat</identifier>
      <definition lang="en" name="B flat">Represents the pitch class B
      lowered by a flat.</definition></concept>
    <concept uuid="en:BSharp">
      <identifier lang="en">BSharp</identifier>
      <definition lang="en" name="B sharp">Represents the pitch class B
      raised by a sharp.</definition></concept>
    <concept uuid="en:BDoubleSharp">
      <identifier lang="en">BDoubleSharp</identifier>
      <definition lang="en" name="B double-sharp">Represents the pitch class B
      raised by a double sharp.</definition></concept>
    <concept uuid="en:BTripleSharp">
      <identifier lang="en">BTripleSharp</identifier>
      <definition lang="en" name="B triple-sharp">Represents the pitch class B
      raised by a triple sharp.</definition></concept>

    <concept uuid="en:CTripleFlat">
      <identifier lang="en">CTripleFlat</identifier>
      <definition lang="en" name="C triple-flat">Represents the pitch class C
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:CDoubleFlat">
      <identifier lang="en">CDoubleFlat</identifier>
      <definition lang="en" name="C double-flat">Represents the pitch class C
      lowered by a double flat.</definition></concept>
    <concept uuid="en:CFlat">
      <identifier lang="en">CFlat</identifier>
      <definition lang="en" name="C flat">Represents the pitch class C
      lowered by a flat.</definition></concept>
    <concept uuid="en:CSharp">
      <identifier lang="en">CSharp</identifier>
      <definition lang="en" name="C sharp">Represents the pitch class C
      raised by a sharp.</definition></concept>
    <concept uuid="en:CDoubleSharp">
      <identifier lang="en">CDoubleSharp</identifier>
      <definition lang="en" name="C double-sharp">Represents the pitch class C
      raised by a double sharp.</definition></concept>
    <concept uuid="en:CTripleSharp">
      <identifier lang="en">CTripleSharp</identifier>
      <definition lang="en" name="C triple-sharp">Represents the pitch class C
      raised by a triple sharp.</definition></concept>

    <concept uuid="en:DTripleFlat">
      <identifier lang="en">DTripleFlat</identifier>
      <definition lang="en" name="D triple-flat">Represents the pitch class D
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:DDoubleFlat">
      <identifier lang="en">DDoubleFlat</identifier>
      <definition lang="en" name="D double-flat">Represents the pitch class D
      lowered by a double flat.</definition></concept>
    <concept uuid="en:DFlat">
      <identifier lang="en">DFlat</identifier>
      <definition lang="en" name="D flat">Represents the pitch class D
      lowered by a flat.</definition></concept>
    <concept uuid="en:DSharp">
      <identifier lang="en">DSharp</identifier>
      <definition lang="en" name="D sharp">Represents the pitch class D
      raised by a sharp.</definition></concept>
    <concept uuid="en:DDoubleSharp">
      <identifier lang="en">DDoubleSharp</identifier>
      <definition lang="en" name="D double-sharp">Represents the pitch class D
      raised by a double sharp.</definition></concept>
    <concept uuid="en:DTripleSharp">
      <identifier lang="en">DTripleSharp</identifier>
      <definition lang="en" name="D triple-sharp">Represents the pitch class D
      raised by a triple sharp.</definition></concept>

    <concept uuid="en:ETripleFlat">
      <identifier lang="en">ETripleFlat</identifier>
      <definition lang="en" name="E triple-flat">Represents the pitch class E
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:EDoubleFlat">
      <identifier lang="en">EDoubleFlat</identifier>
      <definition lang="en" name="E double-flat">Represents the pitch class E
      lowered by a double flat.</definition></concept>
    <concept uuid="en:EFlat">
      <identifier lang="en">EFlat</identifier>
      <definition lang="en" name="E flat">Represents the pitch class E
      lowered by a flat.</definition></concept>
    <concept uuid="en:ESharp">
      <identifier lang="en">ESharp</identifier>
      <definition lang="en" name="E sharp">Represents the pitch class E
      raised by a sharp.</definition></concept>
    <concept uuid="en:EDoubleSharp">
      <identifier lang="en">EDoubleSharp</identifier>
      <definition lang="en" name="E double-sharp">Represents the pitch class E
      raised by a double sharp.</definition></concept>
    <concept uuid="en:ETripleSharp">
      <identifier lang="en">ETripleSharp</identifier>
      <definition lang="en" name="E triple-sharp">Represents the pitch class E
      raised by a triple sharp.</definition></concept>

    <concept uuid="en:FTripleFlat">
      <identifier lang="en">FTripleFlat</identifier>
      <definition lang="en" name="F triple-flat">Represents the pitch class F
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:FDoubleFlat">
      <identifier lang="en">FDoubleFlat</identifier>
      <definition lang="en" name="F double-flat">Represents the pitch class F
      lowered by a double flat.</definition></concept>
    <concept uuid="en:FFlat">
      <identifier lang="en">FFlat</identifier>
      <definition lang="en" name="F flat">Represents the pitch class F
      lowered by a flat.</definition></concept>
    <concept uuid="en:FSharp">
      <identifier lang="en">FSharp</identifier>
      <definition lang="en" name="F sharp">Represents the pitch class F
      raised by a sharp.</definition></concept>
    <concept uuid="en:FDoubleSharp">
      <identifier lang="en">FDoubleSharp</identifier>
      <definition lang="en" name="F double-sharp">Represents the pitch class F
      raised by a double sharp.</definition></concept>
    <concept uuid="en:FTripleSharp">
      <identifier lang="en">FTripleSharp</identifier>
      <definition lang="en" name="F triple-sharp">Represents the pitch class F
      raised by a triple sharp.</definition></concept>

    <concept uuid="en:GTripleFlat">
      <identifier lang="en">GTripleFlat</identifier>
      <definition lang="en" name="G triple-flat">Represents the pitch class G
      lowered by a triple flat.</definition></concept>
    <concept uuid="en:GDoubleFlat">
      <identifier lang="en">GDoubleFlat</identifier>
      <definition lang="en" name="G double-flat">Represents the pitch class G
      lowered by a double flat.</definition></concept>
    <concept uuid="en:GFlat">
      <identifier lang="en">GFlat</identifier>
      <definition lang="en" name="G flat">Represents the pitch class G
      lowered by a flat.</definition></concept>
    <concept uuid="en:GSharp">
      <identifier lang="en">GSharp</identifier>
      <definition lang="en" name="G sharp">Represents the pitch class G
      raised by a sharp.</definition></concept>
    <concept uuid="en:GDoubleSharp">
      <identifier lang="en">GDoubleSharp</identifier>
      <definition lang="en" name="G double-sharp">Represents the pitch class G
      raised by a double sharp.</definition></concept>
    <concept uuid="en:GTripleSharp">
      <identifier lang="en">GTripleSharp</identifier>
      <definition lang="en" name="G triple-sharp">Represents the pitch class G
      raised by a triple sharp.</definition></concept>
    
  </category>
</mica>

=== andigamesandmusic/belle/definitions/map-chromatic-note-to-letter.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <map>en:CTripleFlat en:Letter en:C</map>
  <map>en:CDoubleFlat en:Letter en:C</map>
  <map>en:CFlat en:Letter en:C</map>
  <map>en:C en:Letter en:C</map>
  <map>en:CSharp en:Letter en:C</map>
  <map>en:CDoubleSharp en:Letter en:C</map>
  <map>en:CTripleSharp en:Letter en:C</map>

  <map>en:DTripleFlat en:Letter en:D</map>
  <map>en:DDoubleFlat en:Letter en:D</map>
  <map>en:DFlat en:Letter en:D</map>
  <map>en:D en:Letter en:D</map>
  <map>en:DSharp en:Letter en:D</map>
  <map>en:DDoubleSharp en:Letter en:D</map>
  <map>en:DTripleSharp en:Letter en:D</map>

  <map>en:ETripleFlat en:Letter en:E</map>
  <map>en:EDoubleFlat en:Letter en:E</map>
  <map>en:EFlat en:Letter en:E</map>
  <map>en:E en:Letter en:E</map>
  <map>en:ESharp en:Letter en:E</map>
  <map>en:EDoubleSharp en:Letter en:E</map>
  <map>en:ETripleSharp en:Letter en:E</map>

  <map>en:FTripleFlat en:Letter en:F</map>
  <map>en:FDoubleFlat en:Letter en:F</map>
  <map>en:FFlat en:Letter en:F</map>
  <map>en:F en:Letter en:F</map>
  <map>en:FSharp en:Letter en:F</map>
  <map>en:FDoubleSharp en:Letter en:F</map>
  <map>en:FTripleSharp en:Letter en:F</map>

  <map>en:GTripleFlat en:Letter en:G</map>
  <map>en:GDoubleFlat en:Letter en:G</map>
  <map>en:GFlat en:Letter en:G</map>
  <map>en:G en:Letter en:G</map>
  <map>en:GSharp en:Letter en:G</map>
  <map>en:GDoubleSharp en:Letter en:G</map>
  <map>en:GTripleSharp en:Letter en:G</map>

  <map>en:ATripleFlat en:Letter en:A</map>
  <map>en:ADoubleFlat en:Letter en:A</map>
  <map>en:AFlat en:Letter en:A</map>
  <map>en:A en:Letter en:A</map>
  <map>en:ASharp en:Letter en:A</map>
  <map>en:ADoubleSharp en:Letter en:A</map>
  <map>en:ATripleSharp en:Letter en:A</map>

  <map>en:BTripleFlat en:Letter en:B</map>
  <map>en:BDoubleFlat en:Letter en:B</map>
  <map>en:BFlat en:Letter en:B</map>
  <map>en:B en:Letter en:B</map>
  <map>en:BSharp en:Letter en:B</map>
  <map>en:BDoubleSharp en:Letter en:B</map>
  <map>en:BTripleSharp en:Letter en:B</map>
</mica>

=== andigamesandmusic/belle/definitions/steps.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Steps">Contains concepts relating to step
    distances.</definition>
    
    <concept uuid="en:HalfStep">
      <identifier lang="en">HalfStep</identifier>
      <definition lang="en" name="Half Step">A distance of one chromatic
      semitone.</definition>
    </concept>
    
    <concept uuid="en:WholeStep">
      <identifier lang="en">WholeStep</identifier>
      <definition lang="en" name="Whole Step">A distance of two chromatic
      semitones.</definition>
    </concept>
  </category>
  
  <map>en:A en:B en:WholeStep</map>
  <map>en:B en:C en:HalfStep</map>
  <map>en:C en:D en:WholeStep</map>
  <map>en:D en:E en:WholeStep</map>
  <map>en:E en:F en:HalfStep</map>
  <map>en:F en:G en:WholeStep</map>
  <map>en:G en:A en:WholeStep</map>
</mica>

=== andigamesandmusic/belle/definitions/map-chromatic-note-to-accidental.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <map>en:CTripleFlat en:Accidental en:TripleFlat</map>
  <map>en:CDoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:CFlat en:Accidental en:Flat</map>
  <map>en:C en:Accidental en:Natural</map>
  <map>en:CSharp en:Accidental en:Sharp</map>
  <map>en:CDoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:CTripleSharp en:Accidental en:TripleSharp</map>

  <map>en:DTripleFlat en:Accidental en:TripleFlat</map>
  <map>en:DDoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:DFlat en:Accidental en:Flat</map>
  <map>en:D en:Accidental en:Natural</map>
  <map>en:DSharp en:Accidental en:Sharp</map>
  <map>en:DDoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:DTripleSharp en:Accidental en:TripleSharp</map>

  <map>en:ETripleFlat en:Accidental en:TripleFlat</map>
  <map>en:EDoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:EFlat en:Accidental en:Flat</map>
  <map>en:E en:Accidental en:Natural</map>
  <map>en:ESharp en:Accidental en:Sharp</map>
  <map>en:EDoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:ETripleSharp en:Accidental en:TripleSharp</map>

  <map>en:FTripleFlat en:Accidental en:TripleFlat</map>
  <map>en:FDoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:FFlat en:Accidental en:Flat</map>
  <map>en:F en:Accidental en:Natural</map>
  <map>en:FSharp en:Accidental en:Sharp</map>
  <map>en:FDoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:FTripleSharp en:Accidental en:TripleSharp</map>

  <map>en:GTripleFlat en:Accidental en:TripleFlat</map>
  <map>en:GDoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:GFlat en:Accidental en:Flat</map>
  <map>en:G en:Accidental en:Natural</map>
  <map>en:GSharp en:Accidental en:Sharp</map>
  <map>en:GDoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:GTripleSharp en:Accidental en:TripleSharp</map>

  <map>en:ATripleFlat en:Accidental en:TripleFlat</map>
  <map>en:ADoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:AFlat en:Accidental en:Flat</map>
  <map>en:A en:Accidental en:Natural</map>
  <map>en:ASharp en:Accidental en:Sharp</map>
  <map>en:ADoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:ATripleSharp en:Accidental en:TripleSharp</map>

  <map>en:BTripleFlat en:Accidental en:TripleFlat</map>
  <map>en:BDoubleFlat en:Accidental en:DoubleFlat</map>
  <map>en:BFlat en:Accidental en:Flat</map>
  <map>en:B en:Accidental en:Natural</map>
  <map>en:BSharp en:Accidental en:Sharp</map>
  <map>en:BDoubleSharp en:Accidental en:DoubleSharp</map>
  <map>en:BTripleSharp en:Accidental en:TripleSharp</map>
</mica>

=== andigamesandmusic/belle/definitions/letters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mica PUBLIC
  "-//MICA//MICA DTD//EN"
  "https://raw.githubusercontent.com/andibrae/belle/main/definitions/mica.dtd">
<mica>
  <category>
    <definition lang="en" name="Letters">Contains the note letters.</definition>

    <concept uuid="en:A">
      <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
      <identifier lang="en">A</identifier>
      <definition lang="en" name="A">Represents the pitch class A, which is the
      sixth pitch of C major.</definition>
    </concept>
    
    <concept uuid="en:B">
      <sequence cyclic="true">en:B en:C en:D en:E en:F en:G en:A</sequence>
      <identifier lang="en">B</identifier>
      <definition lang="en" name="B">Represents the pitch class B, which is the
      seventh pitch of C major.</definition>
    </concept>
    
    <concept uuid="en:C">
      <sequence cyclic="true">en:C en:D en:E en:F en:G en:A en:B</sequence>
      <identifier lang="en">C</identifier>
      <definition lang="en" name="C">Represents the pitch class C, which is the
      first pitch of C major.</definition>
    </concept>
    
    <concept uuid="en:D">
      <sequence cyclic="true">en:D en:E en:F en:G en:A en:B en:C</sequence>
      <identifier lang="en">D</identifier>
      <definition lang="en" name="D">Represents the pitch class D, which is the
      second pitch of C major.</definition>
    </concept>
    
    <concept uuid="en:E">
      <sequence cyclic="true">en:E en:F en:G en:A en:B en:C en:D</sequence>
      <identifier lang="en">E</identifier>
      <definition lang="en" name="E">Represents the pitch class E, which is the
      third pitch of C major.</definition>
    </concept>
    
    <concept uuid="en:F">
      <sequence cyclic="true">en:F en:G en:A en:B en:C en:D en:E</sequence>
      <identifier lang="en">F</identifier>
      <definition lang="en" name="F">Represents the pitch class F, which is the
      fourth pitch of C major.</definition>
    </concept>
    
    <concept uuid="en:G">
      <sequence cyclic="true">en:G en:A en:B en:C en:D en:E en:F</sequence>
      <identifier lang="en">G</identifier>
      <definition lang="en" name="G">Represents the pitch class G, which is the
      fifth pitch of C major.</definition>
    </concept>

    <concept uuid="en:Letters">
      <sequence cyclic="true">en:A en:B en:C en:D en:E en:F en:G</sequence>
      <identifier lang="en">Letters</identifier>
      <definition lang="en" name="Letters">Represents the ordered set of all
      note letters.</definition>
    </concept>
  </category>
</mica>
